alter table items drop constraint FKavlbt3fhkpi0ss04bvnuyt0dl;
alter table items drop constraint FK24vm7la8k1qjds0jq9h66q5d9;
alter table items drop constraint FKeyn8cnskax7tgkju8v8g6fdm7;
alter table items drop constraint FKft8pmhndq1kntvyfaqcybhxvx;
alter table models drop constraint FKa3bx5wx21caor8ab44c5xt9ff;
drop table body_types;
drop table items;
drop table marks;
drop table models;
drop table users;

create table body_types (id integer generated by default as identity (start with 1), description varchar(255), primary key (id));
create table items (id integer generated by default as identity (start with 1), mark_id integer, model_id integer, body_type_id integer, year integer, price integer, photo bytea, active boolean, created timestamp, user_id integer, primary key (id));
create table marks (id integer generated by default as identity (start with 1), description varchar(255), primary key (id));
create table models (id integer generated by default as identity (start with 1), description varchar(255), mark_id integer, primary key (id));
create table users (id integer generated by default as identity (start with 1), login varchar(255), password varchar(255), primary key (id));

alter table body_types add constraint UK_9112hdxlx5353i8d818ly1f9n unique (description);
alter table marks add constraint UK_l6nej4njyew2co2wlpbef7cel unique (description);
alter table models add constraint UK_nymfpjoftx05ymg39f944n21t unique (description);
alter table users add constraint UK_ow0gan20590jrb00upg3va2fn unique (login);
alter table items add constraint FKavlbt3fhkpi0ss04bvnuyt0dl foreign key (mark_id) references marks;
alter table items add constraint FK24vm7la8k1qjds0jq9h66q5d9 foreign key (model_id) references models;
alter table items add constraint FKeyn8cnskax7tgkju8v8g6fdm7 foreign key (body_type_id) references body_types;
alter table items add constraint FKft8pmhndq1kntvyfaqcybhxvx foreign key (user_id) references users;
alter table models add constraint FKa3bx5wx21caor8ab44c5xt9ff foreign key (mark_id) references marks;